CREATE TABLE users (id CHAR(36) PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,password_hash VARCHAR(255) NOT NULL,role ENUM('super_admin','owner','manager','staff','customer') NOT NULL DEFAULT 'customer',locale ENUM('ar','en','fr') NOT NULL DEFAULT 'ar',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE activities (id CHAR(36) PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name_ar VARCHAR(120) NOT NULL,name_en VARCHAR(120) NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE tenants (id CHAR(36) PRIMARY KEY,owner_id CHAR(36) NOT NULL,activity_id CHAR(36) NOT NULL,name VARCHAR(160) NOT NULL,slug VARCHAR(100) NOT NULL UNIQUE,country_code CHAR(2) NOT NULL,currency CHAR(3) NOT NULL,locale ENUM('ar','en','fr') NOT NULL DEFAULT 'ar',status ENUM('draft','active','suspended') NOT NULL DEFAULT 'draft',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_id) REFERENCES users(id),FOREIGN KEY(activity_id) REFERENCES activities(id));
CREATE TABLE branches (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,name VARCHAR(160) NOT NULL,city VARCHAR(120) NOT NULL,is_primary BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(tenant_id) REFERENCES tenants(id),INDEX(tenant_id));
CREATE TABLE memberships (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,user_id CHAR(36) NOT NULL,role ENUM('owner','manager','staff') NOT NULL,UNIQUE(tenant_id,user_id),FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE categories (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,name VARCHAR(160) NOT NULL,position INT NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(tenant_id) REFERENCES tenants(id),INDEX(tenant_id,position));
CREATE TABLE products (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,category_id CHAR(36) NOT NULL,name VARCHAR(180) NOT NULL,description TEXT,price DECIMAL(12,2) NOT NULL,image_url TEXT,active BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(category_id) REFERENCES categories(id),INDEX(tenant_id,category_id));
INSERT INTO activities(id,code,name_ar,name_en,enabled) VALUES(UUID(),'restaurant','مطعم','Restaurant',TRUE),(UUID(),'cafe','مقهى','Cafe',TRUE);

CREATE TABLE business_hours (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,branch_id CHAR(36) NOT NULL,day_of_week TINYINT NOT NULL,open_time TIME NULL,close_time TIME NULL,is_closed BOOLEAN NOT NULL DEFAULT FALSE,UNIQUE(branch_id,day_of_week),FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(branch_id) REFERENCES branches(id),INDEX(tenant_id));
CREATE TABLE orders (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,branch_id CHAR(36) NOT NULL,reference_no VARCHAR(32) NOT NULL,status ENUM('new','confirmed','preparing','ready','completed','cancelled') NOT NULL DEFAULT 'new',customer_name VARCHAR(120) NULL,customer_phone VARCHAR(40) NULL,subtotal DECIMAL(12,2) NOT NULL,tax DECIMAL(12,2) NOT NULL DEFAULT 0,total DECIMAL(12,2) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,reference_no),FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(branch_id) REFERENCES branches(id),INDEX(tenant_id,status,created_at));
CREATE TABLE order_items (id CHAR(36) PRIMARY KEY,order_id CHAR(36) NOT NULL,product_id CHAR(36) NOT NULL,name_snapshot VARCHAR(180) NOT NULL,unit_price DECIMAL(12,2) NOT NULL,quantity INT NOT NULL,total DECIMAL(12,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(product_id) REFERENCES products(id),INDEX(order_id));
ALTER TABLE products ADD COLUMN image_key VARCHAR(255) NULL;
CREATE TABLE order_events (id CHAR(36) PRIMARY KEY,order_id CHAR(36) NOT NULL,tenant_id CHAR(36) NOT NULL,event_type VARCHAR(50) NOT NULL,from_status VARCHAR(30) NULL,to_status VARCHAR(30) NULL,actor_user_id CHAR(36) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(tenant_id) REFERENCES tenants(id),INDEX(tenant_id,created_at));

CREATE TABLE IF NOT EXISTS inventory_items (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,name VARCHAR(180) NOT NULL,unit VARCHAR(40) NOT NULL,quantity DECIMAL(12,3) NOT NULL DEFAULT 0,minimum_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tenant_id) REFERENCES tenants(id),INDEX(tenant_id,name));
CREATE TABLE IF NOT EXISTS purchases (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,supplier VARCHAR(180) NOT NULL,total DECIMAL(12,2) NOT NULL DEFAULT 0,status ENUM('draft','received','cancelled') NOT NULL DEFAULT 'received',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tenant_id) REFERENCES tenants(id),INDEX(tenant_id,created_at));
CREATE TABLE IF NOT EXISTS product_ingredients (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,product_id CHAR(36) NOT NULL,inventory_item_id CHAR(36) NOT NULL,quantity DECIMAL(12,3) NOT NULL,FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(inventory_item_id) REFERENCES inventory_items(id),UNIQUE(product_id,inventory_item_id),INDEX(tenant_id));
CREATE TABLE IF NOT EXISTS inventory_movements (id CHAR(36) PRIMARY KEY,tenant_id CHAR(36) NOT NULL,inventory_item_id CHAR(36) NOT NULL,order_id CHAR(36) NULL,movement_type ENUM('purchase','adjustment','order_consume','order_restore') NOT NULL,quantity DECIMAL(12,3) NOT NULL,reference_key VARCHAR(190) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(inventory_item_id) REFERENCES inventory_items(id),FOREIGN KEY(order_id) REFERENCES orders(id),UNIQUE(reference_key),INDEX(tenant_id,created_at));
