import{useEffect,useState}from"react";import{commerceApi}from"../api-commerce";
const days=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
type Row={branchId:string;dayOfWeek:number;openTime:string|null;closeTime:string|null;isClosed:boolean};
export function BusinessHours({slug}:{slug:string}){
 const[branches,setBranches]=useState<any[]>([]);const[branch,setBranch]=useState("");const[rows,setRows]=useState<Row[]>([]);const[saving,setSaving]=useState(false);
 useEffect(()=>{commerceApi.branches(slug).then((r:any)=>{setBranches(r.branches);if(r.branches[0])setBranch(r.branches[0].id)})},[slug]);
 useEffect(()=>{if(!branch)return;commerceApi.hours(slug).then((r:any)=>{const found=r.hours.filter((x:any)=>x.branch_id===branch);setRows(days.map((_,i)=>{const x=found.find((h:any)=>h.day_of_week===i);return{branchId:branch,dayOfWeek:i,openTime:x?.open_time?.slice(0,5)||"09:00",closeTime:x?.close_time?.slice(0,5)||"23:00",isClosed:!!x?.is_closed}}))})},[slug,branch]);
 function patch(i:number,p:Partial<Row>){setRows(v=>v.map(x=>x.dayOfWeek===i?{...x,...p}:x))}
 async function save(){setSaving(true);try{await commerceApi.saveHours(slug,rows)}finally{setSaving(false)}}
 return <section className="hoursBox"><div className="sectionHead"><div><small>الفرع</small><h2>ساعات العمل</h2></div>{branches.length>1&&<select value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}</div>{rows.map(r=><div className="hourRow" key={r.dayOfWeek}><b>{days[r.dayOfWeek]}</b><label><input type="checkbox" checked={r.isClosed} onChange={e=>patch(r.dayOfWeek,{isClosed:e.target.checked})}/> مغلق</label><input type="time" disabled={r.isClosed} value={r.openTime||""} onChange={e=>patch(r.dayOfWeek,{openTime:e.target.value})}/><span>إلى</span><input type="time" disabled={r.isClosed} value={r.closeTime||""} onChange={e=>patch(r.dayOfWeek,{closeTime:e.target.value})}/></div>)}<button className="primary" disabled={saving||!rows.length} onClick={save}>{saving?"جاري الحفظ...":"حفظ ساعات العمل"}</button></section>
}