import{useState}from"react";import{ArrowLeft,Building2,Coffee,LayoutDashboard,LogIn,Menu as MenuIcon,Plus,Settings,Shield,ShoppingBag,Store,UtensilsCrossed,QrCode,Clock3}from"lucide-react";import{useTenant}from"./TenantContext";import{ApiMenu}from"./components/ApiMenu";import{LiveOrders}from"./components/LiveOrders";import{BranchManager}from"./components/BranchManager";import{BusinessHours}from"./components/BusinessHours";import{MenuManager}from"./components/MenuManager";import{localeNames,type Locale}from"./i18n";import{useI18n}from"./I18nContext";import{countries}from"./countries";
type Screen="home"|"login"|"onboarding"|"dashboard"|"menu-admin"|"public-menu"|"orders"|"branches"|"super-admin";
const products=[{id:1,name:"برجر كلاسيك",cat:"البرجر",price:29},{id:2,name:"برجر دجاج",cat:"البرجر",price:27},{id:3,name:"لاتيه",cat:"المشروبات",price:18},{id:4,name:"آيس سبانيش",cat:"المشروبات",price:21}];
export function App(){const{tenant}=useTenant();const activeSlug=tenant?.slug||"";const[screen,setScreen]=useState<Screen>("home");const[storeName,setStoreName]=useState("");const[country,setCountry]=useState("SA");const{locale,setLocale,t}=useI18n();const selectedCountry=countries.find(x=>x.code===country)!;
const go=(s:Screen)=>()=>setScreen(s);
if(screen==="login")return <Shell go={setScreen}><section className="auth"><div className="panel"><div className="mark">N</div><h1>{t("signIn")}</h1><p>{t("signInHint")}</p><label>{t("email")}<input type="email" placeholder="name@example.com"/></label><label>{t("password")}<input type="password" placeholder="••••••••"/></label><button className="primary full" onClick={go("dashboard")}>{t("login")} <ArrowLeft/></button><button className="textBtn" onClick={go("onboarding")}>{t("noAccount")}</button></div></section></Shell>;
if(screen==="onboarding")return <Shell go={setScreen}><section className="flow"><div className="flowHead"><span>01</span><div><h1>{t("createTitle")}</h1><p>{t("createHint")}</p></div></div><div className="formGrid"><label>{t("language")}<select value={locale} onChange={e=>setLocale(e.target.value as Locale)}>{(Object.keys(localeNames) as Locale[]).map(l=><option key={l} value={l}>{localeNames[l]}</option>)}</select></label><label>{t("businessName")}<input value={storeName} onChange={e=>setStoreName(e.target.value)}/></label><label>{t("email")}<input type="email" autoComplete="email" placeholder="name@example.com"/></label><label>{t("address")}<input autoComplete="street-address"/></label><label>{t("city")}<input/></label><label>{t("country")}<select value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(x=><option key={x.code} value={x.code}>{x[locale]}</option>)}</select></label><label>{t("currency")}<input value={selectedCountry.currency} readOnly/></label></div><button className="primary big" onClick={go("dashboard")}>{t("create")} <ArrowLeft/></button></section></Shell>;
if(screen==="dashboard")return <Dashboard name={storeName} go={setScreen}/>;
if(screen==="menu-admin")return <MenuAdmin name={storeName} go={setScreen} slug={activeSlug}/>;
if(screen==="public-menu")return activeSlug?<ApiMenu slug={activeSlug}/>:<div className="emptyBox">أنشئ نشاطك أولاً</div>;if(screen==="orders")return <OperationsPage go={setScreen} slug={activeSlug}/>;if(screen==="branches")return <BranchesPage go={setScreen} slug={activeSlug}/>;
if(screen==="super-admin")return <SuperAdmin go={setScreen}/>;
return <Home go={setScreen}/>;}
function Shell({children,go}:{children:any;go:(s:Screen)=>void}){return <><Header go={go}/><main>{children}</main><Footer go={go}/><MobileNav go={go}/></>}
function Footer({go}:{go:(s:Screen)=>void}){const{t}=useI18n();return <footer className="siteFooter"><div className="footerBrand"><b>NFOODZ</b><p>{t("platformTagline")}</p></div><div><button onClick={()=>go("home")}>{t("home")}</button><button onClick={()=>go("public-menu")}>{t("menu")}</button></div><div><button onClick={()=>go("login")}>{t("login")}</button><button onClick={()=>go("onboarding")}>{t("start")}</button></div><small>© {new Date().getFullYear()} NFOODZ</small></footer>}
function MobileNav({go}:{go:(s:Screen)=>void}){const{t}=useI18n();return <nav className="mobileBottomNav"><button onClick={()=>go("home")}><Store/><span>{t("home")}</span></button><button onClick={()=>go("public-menu")}><MenuIcon/><span>{t("menu")}</span></button><button onClick={()=>go("login")}><LogIn/><span>{t("login")}</span></button></nav>}
function Header({go}:{go:(s:Screen)=>void}){const{locale,setLocale,t,localeNames}=useI18n();return <header><button className="brand clean" onClick={()=>go("home")}><span>N</span><b>NFOODZ</b></button><nav><button onClick={()=>go("home")}>{t("home")}</button><button onClick={()=>go("public-menu")}>{t("menu")}</button></nav><div className="actions"><label className="languageSwitch" aria-label={t("language")}><span>🌐</span><select value={locale} onChange={e=>setLocale(e.target.value as Locale)}>{(Object.keys(localeNames) as Locale[]).map(l=><option key={l} value={l}>{localeNames[l]}</option>)}</select></label><button className="outline" onClick={()=>go("login")}><LogIn/> {t("login")}</button><button className="primary" onClick={()=>go("onboarding")}>{t("start")}</button></div></header>}
function Home({go}:{go:(s:Screen)=>void}){const{t}=useI18n();return <Shell go={go}><section className="hero"><div className="copy"><div className="badge">{t("heroBadge")}</div><h1>{t("heroTitle")}<br/><em>{t("heroAccent")}</em></h1><p>{t("heroText")}</p><div className="heroActions"><button className="primary big" onClick={()=>go("onboarding")}>{t("createBusiness")} <ArrowLeft/></button><button className="outline big" onClick={()=>go("public-menu")}>{t("demoMenu")}</button></div></div><div className="visual"><div className="dash"><div className="dashTop"><div><small>{t("goodMorning")}</small><strong>{t("businessPanel")}</strong></div><span className="avatar">N</span></div><div className="stats"><article><ShoppingBag/><div><small>{t("todayOrders")}</small><b>128</b></div></article><article><Building2/><div><small>{t("branches")}</small><b>1</b></div></article></div><div className="chart"><span>{t("salesGrowth")}</span><div className="bars">{[42,62,50,78,66,94,82].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div></div></div></div></section><section className="activities"><div className="sectionTitle"><span>{t("firstLaunch")}</span><h2>{t("foodBusinesses")}</h2><p>{t("foodIntro")}</p></div><div className="cards"><article><div className="icon"><UtensilsCrossed/></div><h3>{t("restaurants")}</h3><p>{t("restaurantsDesc")}</p></article><article><div className="icon orangeIcon"><Coffee/></div><h3>{t("cafes")}</h3><p>{t("cafesDesc")}</p></article><article className="soon"><div className="plus">+</div><h3>{t("comingActivities")}</h3><p>{t("comingDesc")}</p></article></div></section></Shell>}
function Side({go,active}:{go:(s:Screen)=>void;active:string}){const{t}=useI18n();return <aside><div className="sideBrand"><span>N</span><b>NFOODZ</b></div><small>{t("businessManagement")}</small><button className={active==="dash"?"active":""} onClick={()=>go("dashboard")}><LayoutDashboard/>{t("dashboard")}</button><button className={active==="menu"?"active":""} onClick={()=>go("menu-admin")}><MenuIcon/>{t("menuItems")}</button><button onClick={()=>go("public-menu")}><Store/>{t("viewStore")}</button><button onClick={()=>go("orders")}><ShoppingBag/>{t("orders")}</button><button onClick={()=>go("branches")}><Building2/>{t("branches")}</button><button><Settings/>{t("settings")}</button><hr/><button onClick={()=>go("super-admin")}><Shield/>Super Admin</button></aside>}
function Dashboard({name,go}:{name:string;go:(s:Screen)=>void}){return <div className="workspace"><Side go={go} active="dash"/><section className="work"><div className="workTop"><div><small>الفرع الرئيسي • الرياض</small><h1>{name}</h1></div><button className="primary" onClick={()=>go("menu-admin")}><Plus/>إضافة صنف</button></div><div className="kpis"><article><span>طلبات اليوم</span><b>128</b><small>+12% عن أمس</small></article><article><span>المبيعات</span><b>4,820 <i>ر.س</i></b><small>اليوم</small></article><article><span>الأصناف</span><b>24</b><small>22 متاح</small></article><article><span>الفروع</span><b>1</b><small>الفرع الرئيسي</small></article></div><div className="contentGrid"><article className="box"><h3>أحدث الطلبات</h3>{["#1048 • 86 ر.س","#1047 • 42 ر.س","#1046 • 119 ر.س"].map(x=><div className="row" key={x}><b>{x}</b><span className="status">جديد</span></div>)}</article><article className="box"><h3>إعداد سريع</h3><button className="quick" onClick={()=>go("menu-admin")}><MenuIcon/>إدارة المنيو <ArrowLeft/></button><button className="quick" onClick={()=>go("public-menu")}><Store/>معاينة واجهة العميل <ArrowLeft/></button></article></div></section></div>}
function MenuAdmin({name,go,slug}:{name:string;go:(s:Screen)=>void;slug:string}){return <div className="workspace"><Side go={go} active="menu"/><section className="work"><div className="workTop"><div><small>{name}</small><h1>المنيو والأصناف</h1></div><button className="primary"><Plus/>صنف جديد</button></div><div className="tabs"><button className="active">الكل</button><button>البرجر</button><button>المشروبات</button><button>+ قسم جديد</button></div>{slug?<MenuManager slug={slug}/>:<div className="emptyBox">أنشئ نشاطك أولاً</div>}<div className="productTable">{products.map(p=><div className="productRow" key={p.id}><div className="foodPic">{p.name[0]}</div><div><b>{p.name}</b><small>{p.cat}</small></div><strong>{p.price} ر.س</strong><span className="status">متاح</span><button className="dots">•••</button></div>)}</div></section></div>}
function PublicMenu({name,go}:{name:string;go:(s:Screen)=>void}){const slug="";return <div className="menuPage"><div className="menuCover"><button className="back" onClick={()=>go("home")}>NFOODZ</button><div><span className="open">مفتوح الآن</span><h1>{name}</h1><p>الرياض • الفرع الرئيسي</p></div></div><div className="menuBody"><div className="categoryPills"><button className="active">الكل</button><button>البرجر</button><button>المشروبات</button></div>{slug?<MenuManager slug={slug}/>:<div className="emptyBox">أنشئ نشاطك أولاً</div>}<div className="menuGrid">{products.map(p=><article key={p.id}><div className="menuImg"><span>{p.name[0]}</span></div><div className="menuInfo"><small>{p.cat}</small><h3>{p.name}</h3><p>وصف مختصر للصنف ومكوناته الأساسية.</p><div><b>{p.price} ر.س</b><button>+</button></div></div></article>)}</div></div></div>}
function SuperAdmin({go}:{go:(s:Screen)=>void}){return <div className="workspace"><Side go={go} active="admin"/><section className="work"><div className="workTop"><div><small>NFOODZ Platform</small><h1>Super Admin</h1></div><button className="primary"><Plus/>نشاط جديد</button></div><div className="kpis"><article><span>الأنشطة</span><b>2</b><small>مطاعم ومقاهي</small></article><article><span>المتاجر</span><b>1</b><small>نشط</small></article><article><span>الفروع</span><b>1</b><small>إجمالي</small></article><article><span>المستخدمون</span><b>1</b><small>مالك</small></article></div><article className="box"><h3>الأنشطة المفعلة</h3><div className="row"><b>المطاعم</b><span className="status">مفعل</span></div><div className="row"><b>المقاهي</b><span className="status">مفعل</span></div></article></section></div>}
function OperationsPage({go,slug}:{go:(s:Screen)=>void;slug:string}){return <div className="workspace"><Side go={go} active="orders"/><section className="work"><div className="workTop"><div><small>التشغيل</small><h1>الطلبات</h1></div></div>{slug?<LiveOrders slug={slug}/>:<div className="emptyBox">أنشئ نشاطك أولاً</div>}</section></div>}
function BranchesPage({go,slug}:{go:(s:Screen)=>void;slug:string}){return <div className="workspace"><Side go={go} active="branches"/><section className="work"><div className="workTop"><div><small>إدارة النشاط</small><h1>الفروع</h1></div></div>{slug?<BranchManager slug={slug}/>:<div className="emptyBox">أنشئ نشاطك أولاً</div>}<BusinessHours slug={slug}/><div className="toolsGrid"><article className="box"><QrCode/><h3>QR المنيو</h3><p>رمز مباشر للمنيو العام.</p><img className="qrPreview" src={slug?`/api/qr/${slug}.svg`:""} alt="QR"/></article><article className="box"><Clock3/><h3>ساعات العمل</h3><p>إدارة أوقات العمل ستكون مستقلة لكل فرع.</p></article></div></section></div>}
