export type Country={code:string;currency:string;ar:string;en:string;fr:string};
export const countries:Country[]=[
{code:"SA",currency:"SAR",ar:"السعودية",en:"Saudi Arabia",fr:"Arabie saoudite"},
{code:"AE",currency:"AED",ar:"الإمارات",en:"United Arab Emirates",fr:"Émirats arabes unis"},
{code:"KW",currency:"KWD",ar:"الكويت",en:"Kuwait",fr:"Koweït"},
{code:"QA",currency:"QAR",ar:"قطر",en:"Qatar",fr:"Qatar"},
{code:"BH",currency:"BHD",ar:"البحرين",en:"Bahrain",fr:"Bahreïn"},
{code:"OM",currency:"OMR",ar:"عُمان",en:"Oman",fr:"Oman"},
{code:"EG",currency:"EGP",ar:"مصر",en:"Egypt",fr:"Égypte"},
{code:"JO",currency:"JOD",ar:"الأردن",en:"Jordan",fr:"Jordanie"},
{code:"LB",currency:"LBP",ar:"لبنان",en:"Lebanon",fr:"Liban"},
{code:"MA",currency:"MAD",ar:"المغرب",en:"Morocco",fr:"Maroc"},
{code:"DZ",currency:"DZD",ar:"الجزائر",en:"Algeria",fr:"Algérie"},
{code:"TN",currency:"TND",ar:"تونس",en:"Tunisia",fr:"Tunisie"},
{code:"IQ",currency:"IQD",ar:"العراق",en:"Iraq",fr:"Irak"},
{code:"TR",currency:"TRY",ar:"تركيا",en:"Türkiye",fr:"Turquie"},
{code:"GB",currency:"GBP",ar:"المملكة المتحدة",en:"United Kingdom",fr:"Royaume-Uni"},
{code:"US",currency:"USD",ar:"الولايات المتحدة",en:"United States",fr:"États-Unis"},
{code:"FR",currency:"EUR",ar:"فرنسا",en:"France",fr:"France"},
{code:"DE",currency:"EUR",ar:"ألمانيا",en:"Germany",fr:"Allemagne"},
{code:"NG",currency:"NGN",ar:"نيجيريا",en:"Nigeria",fr:"Nigéria"},
{code:"ZA",currency:"ZAR",ar:"جنوب أفريقيا",en:"South Africa",fr:"Afrique du Sud"},
{code:"KE",currency:"KES",ar:"كينيا",en:"Kenya",fr:"Kenya"},
{code:"GH",currency:"GHS",ar:"غانا",en:"Ghana",fr:"Ghana"},
{code:"ET",currency:"ETB",ar:"إثيوبيا",en:"Ethiopia",fr:"Éthiopie"},
{code:"TZ",currency:"TZS",ar:"تنزانيا",en:"Tanzania",fr:"Tanzanie"},
{code:"UG",currency:"UGX",ar:"أوغندا",en:"Uganda",fr:"Ouganda"},
{code:"RW",currency:"RWF",ar:"رواندا",en:"Rwanda",fr:"Rwanda"},
{code:"SN",currency:"XOF",ar:"السنغال",en:"Senegal",fr:"Sénégal"},
{code:"CI",currency:"XOF",ar:"ساحل العاج",en:"Côte d’Ivoire",fr:"Côte d’Ivoire"},
{code:"CM",currency:"XAF",ar:"الكاميرون",en:"Cameroon",fr:"Cameroun"},
{code:"SD",currency:"SDG",ar:"السودان",en:"Sudan",fr:"Soudan"},
{code:"LY",currency:"LYD",ar:"ليبيا",en:"Libya",fr:"Libye"},
{code:"SO",currency:"SOS",ar:"الصومال",en:"Somalia",fr:"Somalie"},
{code:"DJ",currency:"DJF",ar:"جيبوتي",en:"Djibouti",fr:"Djibouti"},
{code:"MR",currency:"MRU",ar:"موريتانيا",en:"Mauritania",fr:"Mauritanie"},
{code:"ML",currency:"XOF",ar:"مالي",en:"Mali",fr:"Mali"},
{code:"NE",currency:"XOF",ar:"النيجر",en:"Niger",fr:"Niger"},
{code:"BF",currency:"XOF",ar:"بوركينا فاسو",en:"Burkina Faso",fr:"Burkina Faso"},
{code:"BJ",currency:"XOF",ar:"بنين",en:"Benin",fr:"Bénin"},
{code:"TG",currency:"XOF",ar:"توغو",en:"Togo",fr:"Togo"},
{code:"GM",currency:"GMD",ar:"غامبيا",en:"Gambia",fr:"Gambie"},
{code:"GN",currency:"GNF",ar:"غينيا",en:"Guinea",fr:"Guinée"},
{code:"SL",currency:"SLE",ar:"سيراليون",en:"Sierra Leone",fr:"Sierra Leone"},
{code:"LR",currency:"LRD",ar:"ليبيريا",en:"Liberia",fr:"Libéria"},
{code:"AO",currency:"AOA",ar:"أنغولا",en:"Angola",fr:"Angola"},
{code:"MZ",currency:"MZN",ar:"موزمبيق",en:"Mozambique",fr:"Mozambique"},
{code:"ZM",currency:"ZMW",ar:"زامبيا",en:"Zambia",fr:"Zambie"},
{code:"ZW",currency:"ZWG",ar:"زيمبابوي",en:"Zimbabwe",fr:"Zimbabwe"},
{code:"BW",currency:"BWP",ar:"بوتسوانا",en:"Botswana",fr:"Botswana"},
{code:"NA",currency:"NAD",ar:"ناميبيا",en:"Namibia",fr:"Namibie"},
{code:"MW",currency:"MWK",ar:"مالاوي",en:"Malawi",fr:"Malawi"},
{code:"MG",currency:"MGA",ar:"مدغشقر",en:"Madagascar",fr:"Madagascar"},
{code:"MU",currency:"MUR",ar:"موريشيوس",en:"Mauritius",fr:"Maurice"},
{code:"SC",currency:"SCR",ar:"سيشل",en:"Seychelles",fr:"Seychelles"},
{code:"CD",currency:"CDF",ar:"الكونغو الديمقراطية",en:"DR Congo",fr:"RD Congo"},
{code:"CG",currency:"XAF",ar:"الكونغو",en:"Republic of the Congo",fr:"République du Congo"},
{code:"GA",currency:"XAF",ar:"الغابون",en:"Gabon",fr:"Gabon"},
{code:"GQ",currency:"XAF",ar:"غينيا الاستوائية",en:"Equatorial Guinea",fr:"Guinée équatoriale"},
{code:"CF",currency:"XAF",ar:"أفريقيا الوسطى",en:"Central African Republic",fr:"République centrafricaine"},
{code:"TD",currency:"XAF",ar:"تشاد",en:"Chad",fr:"Tchad"},
{code:"BI",currency:"BIF",ar:"بوروندي",en:"Burundi",fr:"Burundi"},
{code:"ER",currency:"ERN",ar:"إريتريا",en:"Eritrea",fr:"Érythrée"},
{code:"SS",currency:"SSP",ar:"جنوب السودان",en:"South Sudan",fr:"Soudan du Sud"},
{code:"CV",currency:"CVE",ar:"الرأس الأخضر",en:"Cabo Verde",fr:"Cap-Vert"},
{code:"KM",currency:"KMF",ar:"جزر القمر",en:"Comoros",fr:"Comores"},
{code:"LS",currency:"LSL",ar:"ليسوتو",en:"Lesotho",fr:"Lesotho"},
{code:"SZ",currency:"SZL",ar:"إسواتيني",en:"Eswatini",fr:"Eswatini"},
{code:"ST",currency:"STN",ar:"ساو تومي وبرينسيب",en:"São Tomé and Príncipe",fr:"Sao Tomé-et-Principe"},
{code:"GW",currency:"XOF",ar:"غينيا بيساو",en:"Guinea-Bissau",fr:"Guinée-Bissau"}
];
