export type Locale="ar"|"en"|"fr";
export const localeNames:Record<Locale,string>={ar:"العربية",en:"English",fr:"Français"};
export const messages={
ar:{home:"الرئيسية",menu:"عرض المنيو",login:"دخول",start:"ابدأ نشاطك",signIn:"تسجيل الدخول",signInHint:"ادخل إلى حساب NFOODZ لإدارة نشاطك.",email:"البريد الإلكتروني",password:"كلمة المرور",noAccount:"ليس لديك حساب؟ أنشئ نشاطك",createTitle:"أنشئ نشاطك الأول",createHint:"المطاعم والمقاهي ضمن تسجيل موحّد. سيتم إنشاء الفرع الرئيسي تلقائياً.",businessName:"اسم النشاط",city:"المدينة",country:"الدولة",currency:"العملة",create:"إنشاء النشاط",language:"اللغة",dashboard:"نظرة عامة",menuItems:"المنيو والأصناف",orders:"الطلبات",branches:"الفروع",settings:"الإعدادات",addItem:"إضافة صنف",loadingMenu:"جاري تحميل المنيو...",openNow:"مفتوح الآن",closedNow:"مغلق الآن",cart:"السلة",orderReceived:"تم استلام طلبك",availableItem:"صنف متاح للطلب",noOrders:"لا توجد طلبات حالياً",customer:"عميل",next:"التالي",primary:"الرئيسي",branch:"فرع",branchName:"اسم الفرع",addBranch:"إضافة فرع",businessHours:"ساعات العمل",closed:"مغلق",to:"إلى",saveHours:"حفظ ساعات العمل",saving:"جاري الحفظ...",categories:"التصنيفات",add:"إضافة",selectCategory:"اختر التصنيف",itemName:"اسم الصنف",price:"السعر",saveItem:"حفظ الصنف",image:"صورة",disable:"إيقاف"},
en:{home:"Home",menu:"View menu",login:"Sign in",start:"Start your business",signIn:"Sign in",signInHint:"Sign in to NFOODZ to manage your business.",email:"Email",password:"Password",noAccount:"No account? Create your business",createTitle:"Create your first business",createHint:"Restaurants and cafés use one unified signup. Your primary branch is created automatically.",businessName:"Business name",city:"City",country:"Country",currency:"Currency",create:"Create business",language:"Language",dashboard:"Overview",menuItems:"Menu & items",orders:"Orders",branches:"Branches",settings:"Settings",addItem:"Add item",loadingMenu:"Loading menu...",openNow:"Open now",closedNow:"Closed now",cart:"Cart",orderReceived:"Order received",availableItem:"Available to order",noOrders:"No orders right now",customer:"Customer",next:"Next",primary:"Primary",branch:"Branch",branchName:"Branch name",addBranch:"Add branch",businessHours:"Business hours",closed:"Closed",to:"to",saveHours:"Save business hours",saving:"Saving...",categories:"Categories",add:"Add",selectCategory:"Select category",itemName:"Item name",price:"Price",saveItem:"Save item",image:"Image",disable:"Disable"},
fr:{home:"Accueil",menu:"Voir le menu",login:"Connexion",start:"Créer mon activité",signIn:"Connexion",signInHint:"Connectez-vous à NFOODZ pour gérer votre activité.",email:"E-mail",password:"Mot de passe",noAccount:"Pas de compte ? Créez votre activité",createTitle:"Créez votre première activité",createHint:"Restaurants et cafés utilisent une inscription unique. La branche principale est créée automatiquement.",businessName:"Nom de l’activité",city:"Ville",country:"Pays",currency:"Devise",create:"Créer l’activité",language:"Langue",dashboard:"Vue d’ensemble",menuItems:"Menu et articles",orders:"Commandes",branches:"Succursales",settings:"Paramètres",addItem:"Ajouter un article",loadingMenu:"Chargement du menu...",openNow:"Ouvert",closedNow:"Fermé",cart:"Panier",orderReceived:"Commande reçue",availableItem:"Disponible à la commande",noOrders:"Aucune commande",customer:"Client",next:"Suivant",primary:"Principal",branch:"Succursale",branchName:"Nom de la succursale",addBranch:"Ajouter une succursale",businessHours:"Horaires",closed:"Fermé",to:"à",saveHours:"Enregistrer les horaires",saving:"Enregistrement...",categories:"Catégories",add:"Ajouter",selectCategory:"Choisir une catégorie",itemName:"Nom de l’article",price:"Prix",saveItem:"Enregistrer l’article",image:"Image",disable:"Désactiver"}
} as const;
export function initialLocale():Locale{const saved=localStorage.getItem("nfoodz_locale");if(saved==="ar"||saved==="en"||saved==="fr")return saved;return"ar"}
export function applyLocale(locale:Locale){localStorage.setItem("nfoodz_locale",locale);document.documentElement.lang=locale;document.documentElement.dir=locale==="ar"?"rtl":"ltr"}
